# run with "--no-sound-null-safety"
name: tommyspec
description: Command Line Spec tool

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0      # state management
  split_view: ^3.2.1        # split view widget
  json_path: ^0.4.2         # js path
  xpath_parse: ^1.0.2       # xpath (TODO update to null-safety version)
  csv: ^5.0.1               # csv parser
  file_picker: ^5.2.5       # openFile and saveFile dialog
  json_annotation: ^4.8.0   # convert class to json
  menubar:                  # native menu bar for Windows/Linux; should be removed once Flutter PlatformMenuBar supports Windows/Linux
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: master

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3      # convert class to json (flutter pub run build_runner build)
  json_serializable: ^6.6.1 # convert class to json

flutter:
  uses-material-design: true
