# run with "--no-sound-null-safety"
name: tommyspec
description: TommySpec project

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0  # state management
  split_view: ^3.2.1    # split view widget
  json_path: ^0.4.2     # js path
  xpath_parse: ^1.0.2   # xpath (update to null-safety version)
  csv: ^5.0.1           # csv parser
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
